version: '3.8'

services:
  meu_postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 0109
      POSTGRES_DB: comercio
      POSTGRES_HOST_AUTH_METHOD: trust  # Permite conexões sem senha (apenas para desenvolvimento)
    ports:
      - "5432:5432"
    volumes:
      - ./BancoSQL/init-comercio.sql:/docker-entrypoint-initdb.d/init-comercio.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d comercio"]
      interval: 5s
      timeout: 5s
      retries: 10